const onlineMapApiKey = "AIzaSyCAl2BYeHX5kBOPezQfJqD8P36d_c3gmlg";
const latitude = "4.326334";
const longitude = "101.139476";

const onlineMapApi = `<iframe width="500" height="500" frameborder="0" style="border: 0" src = "https://www.google.com/maps/embed/v1/place?q=${latitude},${longitude}&key=${onlineMapApiKey}" allowfullscreen"></iframe>`;

const offlineImgLocation = "img/map/fallback_robski_map.png";
const offlineMap = `<img width="500" height="500" frameborder="0" style="border: 0" src="${offlineImgLocation}" allowfullscreen></img>`;

if (typeof Storage !== "undefined") {
	// Code for localStorage
	localStorage.setItem("google_map_online", onlineMapApi);

	/*  Image generated by google map static API through the link below
	"https://maps.googleapis.com/maps/api/staticmap?center=4.326334,101.139476&zoom=15&format=png32&scale=2&size=1280x1280&markers=color:red%7Clabel:R%7C4.326334,101.139476&key=AIzaSyD7X0eY3YSwWE7jXYHbgMidN_UrzqIfkVc"
	*/
	localStorage.setItem("google_map_offline", offlineMap);
} else {
	console.log("Storage is not supported.");
}

function loadOnlineResources() {
	document.querySelector("#google_map").innerHTML = localStorage.getItem(
		"google_map_online"
	);
}

function loadOfflineResources() {
	document.querySelector("#google_map").innerHTML = localStorage.getItem(
		"google_map_offline"
	);
}
